name: Build executables
on: ['push']
jobs:
  build:
    runs-on: ['ubuntu-latest', 'windows-latest'] 
    steps:
    - uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller
    - name: Build executables
      run: |
        pyinstaller otp.py --onefile --name=otp
